name: Test Java Cacher
on: [push, workflow_dispatch]

jobs:
  maven-test:
    name: Maven
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Tester Code
        uses: actions/checkout@v3
      - name: Setup Maven Wrapper
        run: |
          ./install_maven_wrapper.sh
          ./mvnw --version
      - name: Update Test Dependencies
        run: |
          ./mvnw versions:use-latest-releases
      - name: Run Test
        run: |
          ./mvnw test
      - name: Run git test
        run: ./test_git.sh
      - name: Run wget test
        run: ./test_wget.sh
